---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qumulo-pvc-deployment
spec:
  volumeName: qumulo-pv
  storageClassName: qumulo
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 10Gi
